### ISSUE TITLE
Bug: Hypervisor detected when running under `containerd`

### ISSUE THREAD

**Issue by jedsalazar** [edera-dev/am-i-isolated#18]
I have the following podspec, not using the `edera` runtimeclass

```
apiVersion: v1
kind: Pod
metadata:
  name: i-am-not-isolated
spec:
  hostPID: true
  containers:
  - name: i-am-not-isolated
    image: "ghcr.io/edera-dev/am-i-isolated:nightly"
    securityContext:
      privileged: true
    tty: true
```

The hypervisor present test returns true. I'd expect it to return false, unless I'm misunderstanding something or we're testing the presence of a hypervisor and not that we're running in a domU

```
* Checking whether we are running under a hypervisor... present
  + Xen hypervisor control surface detected.
```
