### ISSUE TITLE
Feature Request: Suggested configurations

### ISSUE THREAD

**Issue by jedsalazar** [edera-dev/am-i-isolated#23]
Am I Isolated should provide suggested configurations to mitigate Am I Isolated’s findings. For example 

```
        securityContext:
          capabilities:
            drop:
              - cap_net_admin
```
